# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 47324e65706880feb36738d67800eea17d4f57bda064902ffb18f6be4a58279bb4ccd880abf7f1cbcd5b59f87fbe8391c9db42980de19e3c7697f7cd48e6cab6

test:
  secret_key_base: 34185f6cea062821e01411dc282acef908189fd6d375662d8f78d300899e590d5fb88783eee524ca627fd2b10b8f83bfed479a909e88304b1564033cf81bc162

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
